#!/usr/bin/env bash
# post-changelog.sh — Parse changelog agent JSON output and post an issue comment.
#
# Runs on the host after sandbox cleanup. Working directory is the fullsend
# run output directory (e.g., /tmp/fullsend/agent-changelog-<id>/iteration-1/).
#
# Required env vars:
#   GITHUB_ISSUE_URL  — HTML URL of the issue (e.g., https://github.com/org/repo/issues/42)
#   GH_TOKEN          — GitHub token with issues read/write scope
#
# The agent writes its result to output/agent-result.json (relative to
# the iteration directory). This script finds the most recent iteration's output.

set -euo pipefail

# Find the changelog result JSON. The run dir contains iteration-N/ subdirectories;
# we want the last one's output.
RESULT_FILE=""
for dir in iteration-*/output; do
  if [[ -f "${dir}/agent-result.json" ]]; then
    RESULT_FILE="${dir}/agent-result.json"
  fi
done

if [[ -z "${RESULT_FILE}" ]]; then
  echo "ERROR: agent-result.json not found in any iteration output directory"
  exit 1
fi

echo "Reading changelog result from: ${RESULT_FILE}"

# Validate JSON is parseable.
if ! jq empty "${RESULT_FILE}" 2>/dev/null; then
  echo "ERROR: ${RESULT_FILE} is not valid JSON"
  exit 1
fi

ACTION=$(jq -r '.action' "${RESULT_FILE}")

# Validate and extract repo and issue number from the HTML URL.
if [[ ! "${GITHUB_ISSUE_URL}" =~ ^https://github\.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/issues/[0-9]+$ ]]; then
  echo "ERROR: GITHUB_ISSUE_URL does not match expected pattern: ${GITHUB_ISSUE_URL}"
  exit 1
fi
REPO=$(echo "${GITHUB_ISSUE_URL}" | sed 's|https://github.com/||; s|/issues/.*||')
ISSUE_NUMBER=$(basename "${GITHUB_ISSUE_URL}")

echo "Action: ${ACTION}"
echo "Repo: ${REPO}"
echo "Issue: #${ISSUE_NUMBER}"

case "${ACTION}" in
  changelog-ready)
    SUMMARY=$(jq -r '.summary' "${RESULT_FILE}")
    SEMVER_BUMP=$(jq -r '.semver_bump' "${RESULT_FILE}")
    CHANGES_COUNT=$(jq '.changes | length' "${RESULT_FILE}")

    if [[ -z "${SUMMARY}" || "${SUMMARY}" == "null" ]]; then
      echo "ERROR: action is 'changelog-ready' but no summary provided"
      exit 1
    fi
    if [[ "${CHANGES_COUNT}" -eq 0 ]]; then
      echo "ERROR: action is 'changelog-ready' but changes array is empty"
      exit 1
    fi

    # Build the formatted changelog comment.
    COMMENT="## 📋 Changelog Entry"
    COMMENT="${COMMENT}

**Summary:** ${SUMMARY}

**Suggested version bump:** \`${SEMVER_BUMP}\`

### Changes
"

    # Iterate over each change and build a bullet point.
    for i in $(seq 0 $((CHANGES_COUNT - 1))); do
      CHANGE_TYPE=$(jq -r ".changes[$i].type" "${RESULT_FILE}")
      CHANGE_DESC=$(jq -r ".changes[$i].description" "${RESULT_FILE}")
      CHANGE_PR=$(jq -r ".changes[$i].pr_number // empty" "${RESULT_FILE}")

      BULLET="- **${CHANGE_TYPE}:** ${CHANGE_DESC}"
      if [[ -n "${CHANGE_PR}" ]]; then
        BULLET="${BULLET} (#${CHANGE_PR})"
      fi
      COMMENT="${COMMENT}
${BULLET}"
    done

    COMMENT="${COMMENT}

---
*Generated by the fullsend changelog agent.*"

    echo "Posting changelog comment..."
    printf '%s' "${COMMENT}" | gh issue comment "${ISSUE_NUMBER}" --repo "${REPO}" --body-file -

    echo "Applying changelog-generated label..."
    gh api "repos/${REPO}/issues/${ISSUE_NUMBER}/labels" -f "labels[]=changelog-generated" --silent || {
      echo "WARNING: failed to add changelog-generated label (label may not exist)"
    }
    ;;

  failure)
    REASON=$(jq -r '.reason // "unknown"' "${RESULT_FILE}")

    COMMENT="## 📋 Changelog Generation Failed

The changelog agent could not generate a changelog entry for this issue.

**Reason:** ${REASON}

---
*Generated by the fullsend changelog agent.*"

    echo "Posting failure comment..."
    printf '%s' "${COMMENT}" | gh issue comment "${ISSUE_NUMBER}" --repo "${REPO}" --body-file -
    ;;

  *)
    echo "ERROR: unknown action '${ACTION}' — expected 'changelog-ready' or 'failure'"
    exit 1
    ;;
esac

echo "Post-changelog complete."
